### PR TITLE
Use new option default declaration in Attribute example.

### PR DESCRIPTION
**Pull request by weitzman**
### Disposition
This pull request:

- [X] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
This PR reminds me that there is still a bug in the new option declaration format. It's been a while, and I forget what it is (two or more options, maybe?), but I wanted to fix it before evangelizing that everyone use it. I'm long overdue for that.

**Comment by weitzman** [comment]
Oh, that explains why you never pushed Drush to implement it :)

On PHP 8, you could use named parameters to set option/arg values. That would not help PHP7 but then again PHP7 goes fully EOL in 20 days https://www.php.net/supported-versions.php

**Comment by greg-1-anderson** [comment]
I think I'll start making some b/c-breaking changes to the 5.x branch, including dropping support for PHP 7. I'll make beta releases on 5.x until we're far enough along on Drush 12 to be satisfied that we don't need any further breaking changes.

I might have time today to try to fix the new options declaration format.

**Comment by greg-1-anderson** [comment]
I did some ad-hoc tests; it seems that the new form works for boolean options, but the default value from the method parameter is lost, so options with string values (or bool options that default to true) do not work.

**Comment by greg-1-anderson** [comment]
Starting a PR with a failing test: https://github.com/consolidation/annotated-command/pull/280

**Comment by greg-1-anderson** [comment]
Fixed!

**Comment by greg-1-anderson** [comment]
Cherry-picked to 5.x branch too.

**Pull request merged**
