### PR TITLE
Compatibility with Symfony 5.2+

### PR DESCRIPTION
**Pull request by Naktibalda**
### Disposition
This pull request:

- [x] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes

### Summary
I see many unfinished attempts to implement compatibility with Symfony 5.2+.
I didn't start from scratch, but reused changes implemented by @boedah in #220 and @mkilmanas in #218

I took into account comment that `getNativeDefinition()` can't be used because it isn't part of public API,
so I deconstructed InputOption object and passed parameters to `addOption` method instead,
And fixed HelpTest to support option description changes implemented in symfony/console 5.2.0 and 5.3.0

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Great work; I was looking at this recently and struggling to come up with a way that would work without using an internal API.

I guess `inputOptionSetDescription()` can't work (at least not in a useful way) in newer versions of Symfony Console? Perhaps we should maintain the method, but trigger a warning if it is called. It is unlikely that any clients are overriding AnnotatedCommand and using this method. As for the BC breaks being flagged in Symfony Console, we can just ignore those, and set our BC check to test against a future tagged version of this library. Disable the BC check until that is available.

The failure in HelpTest::testHelp() could be fixed by making it less picky; just assert that the help text contains something that is common to both versions. Maybe the old test is asserting a bad value anyway? It is looking for `<info>list</info>info>`, which is just odd.

**Comment by Naktibalda** [comment]
I solved all issues.

**Comment by greg-1-anderson** [comment]
Looks great; thanks!

**Comment by Naktibalda** [comment]
@greg-1-anderson You can close #218 and #220 and all issues linked to #220 now.

**Comment by boedah** [comment]
> I solved all issues.

Great @Naktibalda !

**Pull request merged**
