### PR TITLE
Fix backward compat, and remove Topic attribute

### PR DESCRIPTION
**Pull request by weitzman**
### Disposition
This pull request:

- [ X] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes

### CODE REVIEW

**Comment by weitzman** [comment]
Accompanying Drush PR https://github.com/drush-ops/drush/pull/5458

**Review by greg-1-anderson — CHANGES_REQUESTED** [review]
Looks good; could you turn the b/c check back on in ci.yml though, and see what it says? We can ignore the b/c break in the help attribute description. That only affects overrides of the help topic, which I don't think folks will do, & I don't care about.

**Comment by weitzman** [comment]
BC check enabled. Its complaining about a PHP8 feature but thats a requirement to use Attributes at all. So maybe its an OK failure.

**Comment by greg-1-anderson** [comment]
There are a ton of bc "breaks" because I switched which version of PHP the composer.lock file is built with. These can be ignored. That means we're down to this:
```
[BC] CHANGED: Type type of property Consolidation\AnnotatedCommand\Hooks\Dispatchers\ReplaceCommandHookDispatcher#$logger changed from having no type to Psr\Log\LoggerInterface|null
[BC] CHANGED: Type type of property Consolidation\AnnotatedCommand\CommandProcessor#$logger changed from having no type to Psr\Log\LoggerInterface|null
[BC] CHANGED: Type type of property Consolidation\AnnotatedCommand\Attributes\Help#$description changed from string to string|null
[BC] CHANGED: The parameter $description of Consolidation\AnnotatedCommand\Attributes\Help#__construct() changed from string to string|null
```
The logger ones are okay, because they are just internal properties. The Help attribute change would only matter if someone overrode the attribute, which folks shouldn't be doing. So I think we're good here.

**Pull request merged**
