### PR TITLE
Fixes: Annotations in Traits are ignored #240

### LINKED ISSUE #240: [BUG] Annotations in Traits are ignored
This is regarding a backwards incompatible change introduced at #237 
As an workaround, avoid version 4.3.2 of this library.

### Steps to reproduce
Create a command using a trait for common options shared among several similar commands.

### Expected behavior
The command runs with no errors and the options are accepted.

### Actual behavior
The options defined at the trait are completely ignored.

### System Configuration
Any

### PR DESCRIPTION
**Pull request by ribeirobreno**
Reverts PR consolidation/annotated-command#237 to fix issue #240 
This bug fix will be compatible with other versions of **4.3.***.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
We'd like to be able to turn on the new behavior via a static class method that sets a protected static boolean. We'll default the boolean to "no trait optimization" in 4.x, default it to "with trait optimization" in 5.x, and from there consider whether commands in traits is something we want to continue to support going forward.

**Comment by weitzman** [comment]
I would prefer to default to optimized in 4.4 (minor version). Use the flag to satisfy folks that must use traits and must upgrade.

**Comment by greg-1-anderson** [comment]
I think it's easier for an app like Drush to turn the flag on than for Robo scripts to have to turn it off to maintain b/c

**Comment by greg-1-anderson** [comment]
Because I already merged changed for 4.4.0 onto the 4.x branch, I released 4.3.3 as a branch off of the 4.3.2.

**Pull request closed without merging**
