### PR TITLE
Stop loading commands from inherited classes (4.x)

### PR DESCRIPTION
**Pull request by DieterHolvoet**
### Disposition
This pull request:

- [ ] Fixes a bug
- [ ] Adds a feature
- [ ] Breaks backwards compatibility
- [ ] Has tests that cover changes

### Summary
This is a 4.x backport of https://github.com/consolidation/annotated-command/pull/272.

### CODE REVIEW

**Comment by Jelle-S** [comment]
This seems like a BC break so should not be in a patch version release?

**Comment by Jelle-S** [comment]
@greg-1-anderson Same remarks as I made back in https://github.com/consolidation/annotated-command/issues/234#issuecomment-923044066
I'm sure we don't fully use Robo as intended, but this BC break has some very unfortunate side effects for us

**Comment by greg-1-anderson** [comment]
Ah, we hit the traits again. The intention of this PR was to prevent command classes that override command classes from double-registering commands. Its affect on traits was unintentional. I don't have time to fix this right now, but a PR to disable the check for methods in traits would be welcome.

**Comment by Jelle-S** [comment]
Actually it's not the traits this time. We have a basic "skeleton" for our deploys since they're always the same: package the code, upload it to the servers, extract, database updates(, config import in case of Drupal), cache clear, update the `current` symlink. This means we have a basic command class that does this, and contains some helpers commands (like a `switch-previous` command we use on rollback to revert the symlink to the previous release). Then depending on the application type (Drupal, Symfony, Laravel, ...) we override (by extending the basic command class) these commands to do some application type specific stuff (like the config import for Drupal). Then, depending on the application, we override those again to do some application specific stuff (some custom drush commands or whatever). But now this won't work anymore.

Again, I realise this is not the "Robo-way", but it *did* work up until now :) 
Same approach as for the traits here would be awesome (boolean flag that defaults to the old behavior).

**Comment by Jelle-S** [comment]
I just read https://github.com/drush-ops/drush/issues/5260#issuecomment-1282989566
I did not find that in documentation anywhere I believe. If this is the way forward it should probably get documented somewhere (to be fair, I might have missed it)

**Comment by greg-1-anderson** [comment]
Not documented, because we didn't expect anyone to organize their code like this. A boolean flag that preserves the b/c behavior is acceptable; PRs welcome.

**Comment by greg-1-anderson** [comment]
Also, I'd recommend that you submit some tests that show that your use case is working. If you get all of your use cases codified in the tests, then we're much less likely to accidentally break behavior that's important.

**Comment by MartinMystikJonas** [comment]
This issue also break our apps. We use universal RoboFile defined in internal framework and extend it with some customisations in our apps. Having different copies of this universal RoboFile would be maintenance nightmare. In fact ability do exactly this was main reason why we choose Robo.

**Comment by emulgeator** [comment]
The same here.
Probably we will fix our robo versions for now, and will try to find a proper workaround. If can't will go for another tool...

**Comment by greg-1-anderson** [comment]
A PR to revert this behavior would be acceptable. It should have a boolean where the default is to allow classes to be overridden.

**Pull request merged**
